const express = require("express");
const routes = express.Router();
const jtControllers = require("../controller/jt");
const userMiddlewares = require('../middleware/user');
const adminMiddlewares = require("../middleware/admin");
const jtMiddleware = require("../middleware/comapny");
routes.post("/edit", adminMiddlewares.isAuth, jtControllers.edit);
routes.post("/create-user-order", userMiddlewares.isAuth, userMiddlewares.isVerfied, jtMiddleware.jtCheck, jtControllers.createUserOrder);
// routes.get("/cities", gltControllers.getAllCities);
// routes.get("/get-all-orders", userMiddlewares.isAuth, gltControllers.getUserOrders);
// routes.get("/print-sticker/:id", gltControllers.getSticker);
// routes.post("/track-order-by-number", userMiddlewares.isAuth, gltControllers.trakingOrderByNum);
module.exports = routes;