const express = require("express");
const routes = express.Router();
const splControllers = require("../controller/spl");
const userMiddlewares = require('../middleware/user');
const adminMiddlewares = require("../middleware/admin");
const saeeMiddleware = require("../middleware/comapny");
routes.get("/token", splControllers.getToken);
routes.post("/crete-new-order", splControllers.creteNewOrder);
routes.post("/get-countries", splControllers.getCountries);
routes.post("/get-districts", splControllers.getDistrict);
routes.get("/get-cities", splControllers.getCities);
module.exports = routes;