const express = require("express");
const routes = express.Router();
const userControllers = require("../controller/user");
const userMiddlewares = require('../middleware/user');
const adminMiddleware = require("../middleware/admin");
routes.post('/signup', userMiddlewares.isValide, userControllers.signUp);
routes.get("/activate-user/:code/:id", userControllers.activateUser);
routes.post('/marketer-signup', userMiddlewares.isValide, userControllers.MarkterSignUp);
routes.post('/login', userControllers.logIn);
routes.get('/get-user-balance', userMiddlewares.isAuth, userControllers.getUserBalance);
routes.get("/resend-activate-code", userMiddlewares.isAuth, userControllers.reSendActivateCode);
routes.post("/send-email-update-password", userControllers.createNewPassword);
routes.post("/update-password", userControllers.updatePassword);
module.exports = routes;